{
	"version": 1722350556,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-3.4.1.min.js",
		"offlineClient.js",
		"images/player-sheet0.png",
		"images/player-sheet1.png",
		"images/player-sheet2.png",
		"images/desertg.png",
		"images/sprite-sheet0.png",
		"images/sprite2-sheet0.png",
		"images/sprite3-sheet0.png",
		"images/sprite4-sheet0.png",
		"images/sprite5-sheet0.png",
		"images/sprite6-sheet0.png",
		"images/sprite7-sheet0.png",
		"images/sprite8-sheet0.png",
		"images/apple-sheet0.png",
		"images/tiledbackground.png",
		"images/sprite9-sheet0.png",
		"images/sprite10-sheet0.png",
		"images/menu-sheet0.png",
		"images/restart-sheet0.png",
		"images/particles.png",
		"media/jump.m4a",
		"media/jump.ogg",
		"media/nff-little-bonus.m4a",
		"media/nff-little-bonus.ogg",
		"media/swipe blade slash clang 03.m4a",
		"media/swipe blade slash clang 03.ogg",
		"media/melodyloops-the-first-light.m4a",
		"media/melodyloops-the-first-light.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}